name: LLVM Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
            git clone https://github.com/Microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.bat
      shell: pwsh
    - name: Patch VCPKG for Release
      run: |
        Add-Content -Path ./vcpkg/triplets/community/x86-windows-static.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Add-Content -Path ./vcpkg/triplets/x64-windows-static.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Set-Content -Path ./vcpkg/scripts/toolchains/windows.cmake ((Get-Content -path ./vcpkg/scripts/toolchains/windows.cmake -Raw) -replace '/Z7','')
      shell: pwsh
    - name: Compile LLVM x86
      run: ./vcpkg/vcpkg.exe install llvm:x86-windows-static
      shell: pwsh
    - name: Compile LLVM x64
      run: ./vcpkg/vcpkg.exe install llvm:x64-windows-static
      shell: pwsh
    - name: Upload x86 build
      uses: actions/upload-artifact@v2
      with:
        name: llvm_x86-windows-static
        path: ./vcpkg/packages/llvm_x86-windows-static/**/*
    - name: Upload x64 build
      uses: actions/upload-artifact@v2
      with:
        name: llvm_x64-windows-static
        path: ./vcpkg/packages/llvm_x64-windows-static/**/*